### ISSUE TITLE
[Google Fonts] How to use non-monospace version of recursive?

### ISSUE THREAD

**Issue by subnut** [arrowtype/recursive#460]
I went to [recursive.design](recursive.design), → _Get Recursive_ (top right) → Set `Monospace` to `Range`  
and I got the following link -

```
https://fonts.googleapis.com/css2?family=Recursive:MONO@0..1&display=swap
```

---

Now, the problem is that, if I specify the following CSS for my webpage -
```css
body {
    font-family: 'Recursive', sans-serif;
}
```
It renders everything in `MONOSPACE`  

---

The problem can be solved by using `Value` instead of `Range`, but that is not an option because I need both non-monospace for normal text and monospace for code.

---

Please help!

**Comment by arrowtype** [comment]
Hey @subnut, sorry to hear that! A few questions for you:
- What OS & browser are you on?
- Do you have Recursive installed locally? If so, do you have a recent release?
- Do you happen to have a test site you could share with me? Even if it’s a codepen, that would be helpful.
- Can you please share a screenshot, just so I see what you’re seeing?

For me, things are still working as I expect [in a quick test on CodePen](https://codepen.io/thundernixon/pen/PoWajdx), but I believe Google Fonts is in the process of updating their hosted version of Recursive, and either that or your local version of the typeface might be causing this issue.

**Comment by arrowtype** [comment]
By the way, a way to "force" the Sans (non-monospace) style would be to add the following CSS to your html/body tag:

```css
body {
    font-variation-settings: "MONO" 0;
}
```

And then you could apply Mono when needed like this:

```css
code, pre {
    font-variation-settings: "MONO" 1;
}
```

But, the default should be `"MONO" 0`, so it’s a surprise that it’s not for you. My best guess is that it might be an OS or browser bug.

**Comment by subnut** [comment]
### What OS/Browser are you on?
![image](https://user-images.githubusercontent.com/56714626/114970518-3c5ede80-9e98-11eb-9190-79823c236cbc.png)

### Do you have recursive installed locally?
No

### Do you happen to have a test site you could share with me? Even if it’s a codepen, that would be helpful.
Umm... no... not right now...   
I don't have a codepen account either.....  
(Please see the attached screenshots below. If they don't help, I shall spin up a test site on github pages)

### Can you please share a screenshot, just so I see what you’re seeing?

Here are the screenshots -
- Your codepen
![image](https://user-images.githubusercontent.com/56714626/114970847-db83d600-9e98-11eb-8239-ece8cbef792f.png)

- Your codepen with `"MONO" 0` (Note that it's still monospaced)
![image](https://user-images.githubusercontent.com/56714626/114970957-0cfca180-9e99-11eb-9f70-b6f9192c3fed.png)

- Your codepen with CSS URL modified from `MONO@0..1` to `MONO@0`
![image](https://user-images.githubusercontent.com/56714626/114971076-41705d80-9e99-11eb-87ac-805f27b20131.png)

#### Also, a gif -
![test](https://user-images.githubusercontent.com/56714626/114971198-7b416400-9e99-11eb-8b89-9cb3e1f69870.gif)

**Comment by subnut** [comment]
Also, a side note -

If I use the `.woff` file directly, there is no problem  
Like I am doing right now in [subnut.github.io](subnut.github.io)

**Comment by subnut** [comment]
Ping @arrowtype  
Can you re-create this issue from the above-provided screenshots?

**Comment by arrowtype** [comment]
Thanks so much for the detailed info! That is helpful.

Quick extra question: what version of Windows are you on?

To be honest, my best guess is that the Google Fonts API is somehow incorrectly detecting your browser/OS or otherwise getting tripped up by it. I can't really think of another reason why the woff2 from GitHub would work when the GF one doesn't.

Two things that would be helpful for you to test, if you're open to it:
- Go to the actual CSS URL of the Google Fonts import, and please paste the contents here
- In that css, go to the font URLs listed. That should download those fonts. Then, you can check whether those are variable, e.g. by going to wakamaifondue.com/beta

**Comment by arrowtype** [comment]
...hopefully that makes sense, but please let me know if not. 

If it does work, please let me know whether you get variable sliders in WakamaiFondue.

**Comment by subnut** [comment]
### Which version of windows?
20H2, which I guess is the latest release?

### The outputs -

- URL
```
https://fonts.googleapis.com/css2?family=Recursive:MONO@0..1&display=swap
```

- Output
```css
/* vietnamese */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vJN7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE5YaERmK-CImKsvxvU-MXGX2fSqasNfUvz2xbXfn1uEQadCCk310tQ1TDA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
/* latin */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vJN7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE5YaERmK-CImKsvxvU-MXGX2fSqasNfUvz2xbXfn1uEQadCCk317tQ0.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
/* vietnamese */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vJN7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE5YaERmK-CImqvTxvU-MXGX2fSqasNfUvz2xbXfn1uEQadCCk310tQ1TDA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
/* latin */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vJN7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE5YaERmK-CImqvTxvU-MXGX2fSqasNfUvz2xbXfn1uEQadCCk317tQ0.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

**Comment by subnut** [comment]
@arrowtype I tried to check the fonts on wakamaifondue.com, but that website seems very unintuitive to me 😅   
Please don't mind 😅 
 
I wasn't able to understand what to look for..

**Comment by arrowtype** [comment]
No worries! That site does a lot. The CSS you pasted is helpful.

When I go to that same URL (on Chrome browser, Mac Catalina), I get the following CSS:

```css
/* vietnamese */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vI-7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE61aHWiJ-CImKsvxvU-MUEnWfSqasB-XlT6ZnI14ZeY9aA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
/* latin */
@font-face {
  font-family: 'Recursive';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/recursive/v23/8vI-7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE61aHWiJ-CImKsvxvU-MUEnWfSqasB-XlTGZnI14ZeY.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

And if I download fonts from the URLs in your CSS vs the CSS I get, I do see that you are getting Monospace, non-variable fonts, while I am getting fonts with a variable `MONO` axis. I tested this with a mac app, Font Goggles.

![image](https://user-images.githubusercontent.com/45946693/115083679-c4170e00-9ed5-11eb-9403-ea47322adf4c.png)

You can see a similar thing in Wakamai Fondue. If you drop a font into the site, the "Tester" section will show a variable axis slider if the font is variable. If it’s static, you don’t get a slider. Here’s what I get with the font Google Fonts returns to me:

![image](https://user-images.githubusercontent.com/45946693/115083927-24a64b00-9ed6-11eb-9768-357f92051ed6.png)
